### PR TITLE
Port code from scope

### PR DESCRIPTION
**Pull request by alepuccetti**
Port code from https://github.com/weaveworks/scope/tree/master/examples/plugins

Once all the plugins will be available here, I will remove them from Scope and update the plugins/README pointing to the new repositories.

### CODE REVIEW

**Comment by 2opremio** [comment]
@alepuccetti CircleCI doesn't seem to be running. Other than that LGTM (provided that you tested it).

**Comment by 2opremio** [comment]
Actually. Instead of copying tools/image-tag can you create a git subtree of `tools/` (https://github.com/weaveworks/build-tools ) ? That's how we do it in all other repositories.

**Comment by alepuccetti** [comment]
> Actually. Instead of copying tools/image-tag can you create a git subtree of tools/ (https://github.com/weaveworks/build-tools ) ? That's how we do it in all other repositories.

I will do it also for the others

**Comment by alepuccetti** [comment]
PTAL

**Comment by alepuccetti** [comment]
I also added the build tools

**Comment by 2opremio** [comment]
LGTM

**Pull request merged**
